version: "3.7"
services:
  spark-master:
    image: fedormalyshkin/spark-master:2.4.5
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker:
    image: fedormalyshkin/spark-worker:2.4.5
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=512m
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
  kudu-impala:
    image:  maple/chd6-impala-kudu:6.2.1
    depends_on:
      - spark-master
    ports:
      - 7050:7050
      - 7051:7051
      - 8051:8051
      - 21000:21000
      - 21050:21050
      - 25000:25000
      - 25010:25010
      - 25020:25020
      - 50070:50070
      - 50075:50075
  docker-hoster:
    image: dvdarias/docker-hoster
    volumes:
       - /var/run/docker.sock:/tmp/docker.sock
       - /etc/hosts:/tmp/hosts
